config/routes.rb
Stinkytrainers::Application.routes.draw do
  
  
  devise_for :users

  resources :sports, :only => [:index, :new, :create, :destroy]

  resources :dashboard, :only => [:index] 
  
  resources :games

  get "ruby-on-rails-tutorial(/*path)" => "tutorial#index"

  root :to => 'home#index'

end

app/models/external_player.rb
class ExternalPlayer < ActiveRecord::Base
  attr_accessible :email
  
  validates :email, :presence => true, :uniqueness => true
  
  has_and_belongs_to_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :at, :location, :sport, :owner, :sport_id, :player_ids, :external_player_ids

  validates :location, :presence => true
  validates :at, :presence => true
  validates :sport, :presence => true
  validates :owner, :presence => true
  
  has_and_belongs_to_many :players, :class_name => 'User', :order => "users.email ASC"
  has_and_belongs_to_many :external_players, :order => "external_players.email ASC"
  belongs_to :sport
  belongs_to :owner, :class_name => 'User'
  
  validate :cannot_create_a_game_in_the_past, :on => :create
   
  def over?
    Time.now > self.at
  end

  def add_new_player(email)
    
    if (player = User.find_by_email(email))
      players << player
      return
    end
    
    if (player = ExternalPlayer.find_by_email(email))
      external_players << player
      return
    end
    
    external_players.create!(:email => email)
    
  end
  
  private
  
  def cannot_create_a_game_in_the_past
    return unless self.at
    self.errors.add(:at, 'Cannot create a game in the past') if self.over?
  end

end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :name

  validates :name,   :presence => true, :uniqueness => true
  
  has_and_belongs_to_many :users
  has_many :games
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_and_belongs_to_many :sports
  has_and_belongs_to_many :games
  
  has_many :players, :through => :games, :uniq => true
  has_many :external_players, :through => :games, :uniq => true
  
  has_many :owned_games, :class_name => 'Game', :foreign_key => :owner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @owned_games = current_user.owned_games
    @games = current_user.games
  end

  def new
    @game = Game.new
    @game.players << current_user
  end

  def create
    @game = Game.new(params[:game])
    @game.owner = current_user
    
    if @game.save
      @game.add_new_player(params[:new_player]) unless params[:new_player].blank?
  		redirect_to game_path(@game)
  	else
  		render :template => 'games/new.html.erb'
  	end
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      redirect_to game_path(@game)
    else
      render :template => 'games/edit.html.erb'
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @sports = Sport.all
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(params[:sport])
    
   	if @sport.save
  		redirect_to(sports_path)
  	else
  		render :template => 'sports/new.html.erb'
  	end
  end

  def destroy
    Sport.destroy(params[:id])
    redirect_to(sports_path)
  end
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
  def index
    render params[:path]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/tutorial_helper.rb
module TutorialHelper
end

app/views/dashboard/index.html.erb
<h1 class="banner">Stinky Trainers Dashboard</h1>

app/views/games/_form.html.erb
<%= form_for @game do |f| %>

  <div class="control-group <%= "error" if @game.errors.any? %>">
    <%= f.label :sport_id, 'Sport', :class => 'control-label' %>
    <div class='controls'>
      <%= f.select :sport_id, options_from_collection_for_select(Sport.all, :id, :name, @game.sport.try(:id)), {:include_blank => true}, {:class => 'input-xlarge' } %>
    </div>
  </div>

  <div class="control-group <%= "error" if @game.errors.any? %>">
    <%= f.label :location, :class => 'control-label' %>
    <div class='controls'>
      <%= f.text_field :location, :class => 'input-xlarge' %>
    </div>
  </div>

  <div class="control-group <%= "error" if @game.errors.any? %>">
    <%= f.label :at, :class => 'control-label' %>
    <div class='controls'>
      <%= f.datetime_select "at",{}, :class => 'input-small' %>
    </div>
  </div>

  <div class="control-group <%= "error" if @game.errors.any? %>">
    <%= label_tag :players, nil, :class => 'control-label' %>
    <div class='controls' id="players">
		<% current_user.players.each do |player| %>
		 <%= check_box_tag "game[player_ids][]", player.id, @game.players.include?(player), :id => "game_player_id_#{player.id}" %> <%= player.email %><br/>
	    <% end %>
	    <%= hidden_field_tag "game[player_ids][]" %>
    </div>
  </div>

  <div class="control-group <%= "error" if @game.errors.any? %>">
    <%= label_tag :players_not_on_stinky_trainers, nil, :class => 'control-label' %>
    <div class='controls' id="external_players">
  		<% current_user.external_players.each do |external_player| %>
			<%= check_box_tag "game[external_player_ids][]", external_player.id, @game.external_players.include?(external_player), :id => "game_external_player_id_#{external_player.id}" %> <%= external_player.email %><br/>
  		<% end %>
        <%= hidden_field_tag "game[external_player_ids][]" %>
    </div>
  </div>

  <div class="control-group <%= "error" if @game.errors.any? %>">
    <%= label_tag :new_player, nil, :class => 'control-label' %>
    <div class='controls'>
      <%= text_field_tag :new_player, nil, :class => 'input-xlarge' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit @game.new_record? ? 'Create Game' : 'Update Game', :class => 'btn btn-primary' %>
    <%= link_to 'Back', games_path, :class => 'btn' %>
  </div>

<% end %>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<%= render 'form' %>

app/views/games/index.html.erb
<h1>Games#index</h1>

<h2>Game I have created</h2>
<table id="owned_games">
	<% @owned_games.each do |game| %>
	<tr data-row='game_<%= game.id %>'>
		<td><%= game.sport.name %></td>
		<td><%= game.location %></td>
		<td><%= game.at %></td>
		<td><%= link_to 'edit', edit_game_path(game) %></td>
		<td><%= link_to 'show', game_path(game) %></td>
	</tr>
	<% end %>
</table>

<h2>Game I am playing</h2>
<table id="games">
	<% @games.each do |game| %>
	<tr data-row='game_<%= game.id %>'>
		<td><%= game.sport.name %></td>
		<td><%= game.location %></td>
		<td><%= game.at %></td>
	</tr>
	<% end %>
</table>

<%= link_to 'Create Game', new_game_path, :class => 'btn btn-primary' %>

app/views/games/new.html.erb
<h1>Games#new</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<h1>Games#show</h1>

<div id="game">
	<p><%= @game.location %></p>
	<p><%= @game.at %></p>
	<p><%= @game.sport.name %></p>
</div>

<h2>Players</h2>
<ul id="players">
	<% @game.players.each do |player| %>
		<li><%= player.email %></li>
	<% end %>
</ul>

<h2>Players outside Stinky Trainers</h2>
<ul id="external_players">
	<% @game.external_players.each do |player| %>
		<li><%= player.email %></li>
	<% end %>
</ul>

<div><%= link_to 'Destroy', game_path(@game), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-mini' %></div>	

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/home/index.html.erb
<%= content_for :title,  "Welcome to Stinky Trainers" %>

<div class="well">
	<p>Stinky trainers is a website that let's you organise your sports life with your friends:</p>
	<ul>
		<li>Organise games.</li>
		<li>Track your results.</li>
		<li>Monitor your progress.</li>
		<li>Laugh at your friends when they lose.</li>
		<li>Tell them how lucky they were when they win.</li>
	</ul>
</div>

<div class="well">
	<p>Stinky trainers is also an in-depth <a href="/ruby-on-rails-tutorial/">Ruby on Rails Tutorial</a> for anyone wanting to learn the kind of web-development that just keeps on giving.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StinkyTrainers" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="favicon.ico" rel="shortcut icon">

    <link href='http://fonts.googleapis.com/css?family=Sonsie+One|Vast+Shadow' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>

  </head>
  <body class="stinky">
    <%= render 'shared/google_analytics' %>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <a class="brand" href="/">Stinkytrainers</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to "dashboard", dashboard_index_path  %></li>
                <li><%= link_to "games", games_path  %></li>
                <li><%= link_to "sports", sports_path  %></li>
	   		    <li><%= link_to "sign-out", destroy_user_session_path, :method => :delete  %></li>
              <% else %>
	   		        <li><%= link_to "Sign In", new_user_session_path %></li>
              <% end %>
            </ul>
            <ul class="nav pull-right">
              <li><%= link_to "Ruby On Rails Tutorial", :controller => '/tutorial' %></li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
	  
	
    </div>
	
    <h1 class="banner"><%= yield :title %></h1>
	
    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
			
				<%= yield %>
			
            </div>
            <div class="span3">
				&nbsp;
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Stinky Trainers 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/tutorial.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stinkytrainers" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
    <%= render 'shared/google_analytics' %>
    <% unless Rails.env.test? %>
      <div id="fb-root"></div>
      <script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      </script>
    <% end %>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "StinkyTrainers Tutorial", {:controller => '/tutorial'}, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Go to the application", "/"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span8" id='tutorial'>
            <%= yield %>
          </div>
          <div class="span4">
            <%= render 'shared/tutorial/slidebar' %>
          </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Stinky Trainers 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_google_analytics.html.erb
<% unless Rails.env.development? || Rails.env.test? %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-34524204-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% end %>

app/views/shared/tutorial/_slidebar.html.erb
<div class="well sidebar-nav">
  <h4>Index</h4>
  <!--<ul class="nav nav-list">
    <li class="nav-header">Get redy to roll</li>
    <li><%= link_to "Install Ruby", "#"  %></li>
    <li><%= link_to "Install RVM", "#"  %></li>
    <li><%= link_to "Install RBenv", "#"  %></li>
    <li><%= link_to "Install bundle and rails gems", "#"  %></li>
  </ul>-->
  <ul class="nav nav-list">
    <li class="nav-header">Building Application</li>
    <li><%= link_to "1. Stinky Trainers", "/ruby-on-rails-tutorial/1-setting-up-the-application.html"  %></li>
    <li><%= link_to "2. Create the home page", "/ruby-on-rails-tutorial/2-create-the-home-page.html"  %></li>
    <li><%= link_to "3. Create the Dashboard Page", "/ruby-on-rails-tutorial/3-create-the-dashboard-view.html"  %></li>
    <li><%= link_to "4. Secure the dashboard", "/ruby-on-rails-tutorial/4-secure-the-dashboard-view.html"  %></li>
    <li><%= link_to "5. Create the Sports Model", "/ruby-on-rails-tutorial/5-create-the-sport-model.html"  %></li>
    <li><%= link_to "6. The Sports Controller and Views", "/ruby-on-rails-tutorial/6-create-the-sports-controller.html"  %></li>
    <li><%= link_to "7. The Game Model", "/ruby-on-rails-tutorial/7-create-the-game-model.html"  %></li>
    <li><%= link_to "8. The Game Controller and View", "/ruby-on-rails-tutorial/8-create-the-game-controller-and-view.html"  %></li>
  </ul>
</div><!--/.well -->
        

app/views/sports/create.html.erb
<h1>Sports#create</h1>
<p>Find me in app/views/sports/create.html.erb</p>

app/views/sports/destroy.html.erb
<h1>Sports#destroy</h1>
<p>Find me in app/views/sports/destroy.html.erb</p>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table class='table'>
  <thead>
    <tr>
      <th width=90%>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr data-row='<%= sport.id %>' style='background-color: white; <%= cycle('opacity: 0.9','opacity: 0.7') %>'>
        <td><%= sport.name %></td>
        <td><%= link_to 'Destroy', sport_path(sport), :method => :delete, :data =>{ confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-mini' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Sport', new_sport_path, :class => 'btn btn-primary' %>

app/views/sports/new.html.erb
<h1>Create a new Sport</h1>
<%= form_for @sport, :class => 'form-horizontal' do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class='controls'>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="form-actions">
    <%= submit_tag 'Create Sport', :class => 'btn btn-primary' %>
    <%= link_to 'Back', sports_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tutorial/index.html.erb
<h1>Stinky Trainers Tutorial</h1>
<p>Stinky Trainers is a tutorial that builds complete Rails Application from 'rails new' through to 'cap deploy'. It's an alternative to the 'build a Rails App in 15 mins' and intended for anyone serious enough about learning to put in a good few hours of learning so that they get it right.</p>

<p>We're experienced Rails trainers that explain everything we're doing along the way. By the time you've finished the tutorial you'll have built a start-to-finish textbook rails app & ready to build the next one for yourself.</p>

<p>You'll find comments sections throughout the tutorial so feel free to ask a question or make an observation.</p>

<p>This course covers:</p>

<ul>
<li>Up and running with Twitter Bootstrap</li>
<li>RESTful routing</li>
<li>Secure login with Devise</li>
<li>Data access with ActiveRecord and data validation with ActiveModel</li>
<li>Functional testing with Capybara, unit testing with RSpec, mocking objects with Factory Girl.</li>
<li>Image uploads with Paperclip</li>
<li>Deployment to Heroku</li>
</ul>

<p>There's a lot to do but if you follow it carefully you'll get a good feel for the 'Rails Way' and, hopefully, enjoyed the experience.</p>

<p>We run courses at the Docklands Academy near Canary Wharf. If you're an individual then sign-up and we'll let you know when we have enough people to run our next 3 day course.</p>

<p>If your a business looking to train a number of developers we typically teach on-site so contact us for more details.</p>

<a href="/ruby-on-rails-tutorial/1-setting-up-the-application.html" class="btn btn-primary">Start the tutorial</a>